### ISSUE TITLE
Adding this api wrapper to the aghpb api wrappers list.

### ISSUE THREAD

**Issue by THEGOLDENPRO** [JoshiCodes/AGHPB4J#1]
Hi,

Creator of [aghpb-api](https://github.com/THEGOLDENPRO/aghpb-api) here.

I really appreciate 🧡 you creating an API wrapper for aghpb-api in ☕ Java; do you mind me adding / linking your API wrapper under the [aghpb-api readme](https://github.com/THEGOLDENPRO/aghpb-api?tab=readme-ov-file#-api-wrappers) so more people can find it easier?

**Comment by JoshiCodes** [comment]
Hey there, thank you for your kind words!
I'd be honored to have my wrapper linked in the readme, it would be great to help more people find and use it!

**Comment by THEGOLDENPRO** [comment]
Done 👍
